/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import { Web3Button, ConnectWallet, useAddress, useContract, useContractRead } from "@thirdweb-dev/react";
import toast from 'react-hot-toast';
import { ethers } from 'ethers';

export default function Home() {
  const tokenId = 0; // the id of the NFT you want to claim
  const quantity = 1; // how many NFTs you want to claim
  const address = useAddress();
  const { contract } = useContract("0x05C2D4Fdc3C2Dfda229EDe73094326b2F7e7e77C", "edition-drop")
  const { data: totalSupply } = useContractRead(contract, "totalSupply", tokenId)

  const handleMint = async () => {
    if (address) {
      const nfts = await contract.getOwned(address);
      const notification = toast.loading("Minting Your Free NFT");

      if (nfts.length < 1) {
        try {
          const tx = await contract.claimTo(address, tokenId, quantity);
          const receipt = tx.receipt;
          toast.success("NFT Minted successfully!", {
            id: notification,
          });
          console.log("Contract call success ==> ", receipt)
        } catch (err) {
          toast.error("Whoops, something went wrong!", {
            id: notification,
          });
          console.error("contract call failure: ", err);
        }
      } else {
        toast.error("You already own a Free NFT", {
          id: notification,
        });
      }
    }
    else {
      toast.error("Connect Your Wallet First")
    }
  }
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-yellow-200 via-emerald-200 to-yellow-200 h-screen'>
        <div className="flex justify-between items-center p-1 bg-emerald-200">
          <p className="text-center text-4xl font-bold">NFT Minter dApp</p>
          <ConnectWallet />
        </div>
        <div className="flex justify-center items-center mt-10">
          <div className="max-w-[500px] mr-10">
            <p className="text-2xl font-bold m-2">Bored Ape Pizza</p>
            <p className="text-md font-semibold m-2">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam voluptatum commodi nobis, aliquid beatae exercitationem maiores molestias deleniti ratione saepe aperiam ex assumenda nostrum, facilis dignissimos laboriosam eveniet alias aspernatur a recusandae magni sequi rem.</p>
          </div>
          <div>
            <img src="https://lh3.googleusercontent.com/MpP1Fr_VPO6b5YBFRgfDcFCkd9C-Ghcgc3nXOD-tctSs_RR6-IH9lJQKgTaSMrnJN59CSpKZ_3FHz6CDP7Kzu0fPM52JBL9ohOUW2QU=w1400-k" alt="NFT Image" className="w-[400px] rounded-lg" />
            <p className="text-center text-xl font-bold mt-2">Total minted: {(
              totalSupply ? Number(totalSupply) : <span>Loading...</span>)}</p>
          </div>
        </div>
        <div className="flex justify-center mt-10 space-x-2">
          <button className="bg-black p-2 rounded-lg shadow-md text-xl text-white font-semibold"
            onClick={handleMint}
          >Free Gasless Mint</button>
        </div>
      </div>
    </div>
  )
}
